AllCops:
  TargetRubyVersion: 2.3

Layout/DotPosition:
  EnforcedStyle: trailing

Metrics/BlockLength:
  Exclude:
    - "*.gemspec"

Style/FrozenStringLiteralComment:
  Exclude:
  - "Gemfile"
  - "Rakefile"
  - "bin/*"
  - "spec/**/*.rb"

Style/StringLiterals:
  EnforcedStyle: double_quotes
